In [2]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

# Load env
load_dotenv()
engine = create_engine(f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}")

# Check row count
query = "SELECT COUNT(*) FROM pitch_data;"
count = pd.read_sql(query, engine)
print(count)

    count
0  721611

In [3]:
df = pd.read_sql("SELECT * FROM pitch_data LIMIT 10;", engine)
df.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle
0,ST,2024-09-10,84.3,-2.91,5.58,"Hodge, Porter",669257,687863,field_out,hit_into_play,...,1,0,2.0,1.0,4.0,1.0,3.09,-1.30,-1.30,35.5
1,ST,2024-09-10,85.0,-2.73,5.55,"Hodge, Porter",669257,687863,None,ball,...,1,0,2.0,1.0,4.0,1.0,2.95,-1.50,-1.50,40.6
2,ST,2024-09-10,84.8,-2.78,5.69,"Hodge, Porter",669257,687863,None,called_strike,...,1,0,2.0,1.0,4.0,1.0,2.98,-1.40,-1.40,37.6
3,FF,2024-09-10,97.6,-2.62,5.81,"Hodge, Porter",669242,687863,field_out,hit_into_play,...,1,3,2.0,1.0,4.0,1.0,0.95,0.19,-0.19,44.1
4,ST,2024-09-10,84.7,-2.80,5.64,"Hodge, Porter",669242,687863,None,called_strike,...,1,3,2.0,1.0,4.0,1.0,3.20,-1.25,1.25,37.4

In [6]:
query = """
SELECT pitcher, stand, balls, strikes, inning, outs_when_up, pitch_type
FROM pitch_data
WHERE pitch_type IS NOT NULL
"""
test_df = pd.read_sql(query, engine)

pitch_map = {
    'FF': 'Four-Seam Fastball',
    'FT': 'Two-Seam Fastball',
    'SI': 'Sinker',
    'FC': 'Cutter',
    'SL': 'Slider',
    'CH': 'Changeup',
    'CU': 'Curveball',
    'KC': 'Knuckle Curve',
    'KN': 'Knuckleball',
    'FS': 'Split-Finger Fastball',
    'ST': 'Sweeper',
    'EP': 'Eephus',
    'SC': 'Screwball',
    'FO': 'Forkball'
}

test_df['pitch_type_full'] = test_df['pitch_type'].map(pitch_map)

test_df.head(20)

,pitcher,stand,balls,strikes,inning,outs_when_up,pitch_type,pitch_type_full
0,687863,R,1,1,9,1,ST,Sweeper
1,687863,R,0,1,9,1,ST,Sweeper
2,687863,R,0,0,9,1,ST,Sweeper
3,687863,L,0,1,9,0,FF,Four-Seam Fastball
4,687863,L,0,0,9,0,ST,Sweeper
5,660813,R,0,2,9,2,FF,Four-Seam Fastball
6,660813,R,0,1,9,2,SI,Sinker
7,660813,R,0,0,9,2,SI,Sinker
8,660813,L,2,1,9,2,SI,Sinker
9,660813,L,1,1,9,2,FC,Cutter
10,660813,L,0,1,9,2,SI,Sinker
11,660813,L,0,0,9,2,FC,Cutter
12,660813,R,1,2,9,2,SL,Slider
13,660813,R,1,1,9,2,SI,Sinker
14,660813,R,1,0,9,2,SL,Slider
15,660813,R,0,0,9,2,SI,Sinker
16,660813,R,2,2,9,1,SI,Sinker
17,660813,R,1,2,9,1,SL,Slider
18,660813,R,1,1,9,1,SL,Slider
19,660813,R,0,1,9,1,SI,Sinker